version: '2.1'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=alio
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    networks:
      influx:
        ipv4_address: 10.18.1.2

  telegraf:
    container_name: telegraf
    image: telegraf:latest
    ports:
      - '8125:8125/udp'
      - '8092:8092/udp'
      - '8094:8094'
    networks:
      influx:
        ipv4_address: 10.18.1.3
    extra_hosts:
      - "influxdb:10.18.1.2"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root
    networks:
      influx:
        ipv4_address: 10.18.1.4
    extra_hosts:
      - "influxdb:10.18.1.2"

networks:
  influx:
    driver: bridge
    ipam:
     config:
       - subnet: 10.18.1.0/16
         gateway: 10.18.1.1
