version: '2'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    network_mode: "host"
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=alio
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    network_mode: "host"
    ports:
      - '8125:8125/udp'
      - '8092:8092/udp'
      - '8094:8094'
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root
